"""empty message

Revision ID: 68ac40a51877
Revises: 19335a800312
Create Date: 2020-05-27 15:29:48.857866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ac40a51877'
down_revision = '19335a800312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Show', 'artist_image_link')
    op.drop_column('Show', 'artist_name')
    op.drop_column('Show', 'venue_name')
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('Show', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('Artist', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
